title: Marketing Club
description: Marketing Club that helps SDRs build their skills and career options
baseurl: "/"
collections:
  pages:
    output: true
destination: ./../public/
collections:
  pages:
    output: true
url: https://keetro.club
title: Keetro.club
# defaults:
#   -
#     scope:
#       path: "pages"
#       type: "pages"
#     values:
#       layout: "default"
#   -
#     scope:
#       path: "lps" # an empty string here means all files in the project
#       type: "pages"
#     values:
#       layout: "landing_pages"
